import { type MetadataRoute } from "next";

import { buildSitemapEntries } from "@/lib/sitemap-data";

// The URL list + per-URL <lastmod> are computed in @/lib/sitemap-data so
// the same data is shared with the IndexNow trigger route handler at
// src/app/api/indexnow/route.ts. Per-URL `lastModified` is the most
// recent commit timestamp across every file that contributes to the
// URL's rendered content — see src/lib/generated/content-mtimes.json,
// regenerated by `scripts/generate-content-mtimes.mjs` (the `prebuild`
// npm hook). Static build-timestamp lastmods are explicitly NOT used:
// Google's docs warn that a sitemap whose every URL carries the same
// build time will be ignored as a lastmod signal.
export default function sitemap(): MetadataRoute.Sitemap {
  return buildSitemapEntries();
}
